[package]
name = "rust-bench"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.8"
diffusionx = "0.11.1"

[[bench]]
name = "bm"
harness = false

[[bench]]
name = "random"
harness = false

[[bench]]
name = "ou"
harness = false
