[package]
name = "rust-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
diffusionx = "0.11.0"
rand = "0.9.2"
rand_distr = "0.5.1"
rand_xoshiro = "0.7.0"
rayon = "1.10"

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "bm"
harness = false

[[bench]]
name = "random"
harness = false
